Process exited with status 1: Traceback (most recent call last):
  File "/Users/tung/Library/CloudStorage/OneDrive-Personal/Documents/~UTS Spring 2025/36127 Innovation Lab Capstone Project/Code/AutoKaggle/multi_agents/competition/titanic/pre_eda/pre_eda_run_code.py", line 96, in <module>
    generated_code_function()
  File "/Users/tung/Library/CloudStorage/OneDrive-Personal/Documents/~UTS Spring 2025/36127 Innovation Lab Capstone Project/Code/AutoKaggle/multi_agents/competition/titanic/pre_eda/pre_eda_run_code.py", line 14, in generated_code_function
    train_data = pd.read_csv('train.csv')
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tung/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tung/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tung/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tung/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/tung/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'
